#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec 2>&1 \
        s6-setuidgid abc /usr/sbin/sockd -f /config/sockd.conf -p /config/sockd.pid
else
    exec 2>&1 \
        /usr/sbin/sockd -f /config/sockd.conf -p /config/sockd.pid
fi
