name: container - drone-fpm

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths:
      - .github/workflows/drone-fpm.yml
      - drone-fpm/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/drone-fpm.yml
      - drone-fpm/**

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: divialth/drone-fpm
  # renovate: datasource=rubygems depName=fpm versioning=ruby
  FPM_VERSION: 1.15.1


jobs:
  build-app:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout drone-fpm repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          repository: betterengineering/drone-fpm

      - name: Prepare Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: gem install --no-document fpm -v ${{ env.FPM_VERSION }}

      - name: build entrypoint generator
        run: make build

      - name: generate entrypoint
        run: ./out/generate-entrypoint

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: entrypoint
          path: out/entrypoint.sh


  build-container:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
      - build-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: entrypoint
          path: drone-fpm

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: drone-fpm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
