name: keepalive

on:
  schedule:
    - cron: '30 4 * * *'

jobs:
  keepalive:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          committer_username: "divialth-bot"
          committer_email: "bot@dummy-domain.tld"
