name: keepalive

on:
  schedule:
    - cron: '30 4 * * *'

jobs:
  keepalive:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: "divialth-bot"
          committer_email: "bot@dummy-domain.tld"
