name: keepalive

on:
  schedule:
    - cron: '30 4 * * *'

jobs:
  keepalive:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: "divialth-bot"
          committer_email: "bot@dummy-domain.tld"
